"""add details in table payment

Revision ID: 052efd1db35d
Revises: 
Create Date: 2025-05-09 22:32:06.460235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052efd1db35d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('screenshot_path', sa.String(length=255), nullable=True))
    op.add_column('payment', sa.Column('transfer_note', sa.String(length=255), nullable=True))
    op.add_column('payment', sa.Column('ewallet_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'ewallet_number')
    op.drop_column('payment', 'transfer_note')
    op.drop_column('payment', 'screenshot_path')
    # ### end Alembic commands ###
