"""Add chat

Revision ID: 1ebbdcf51b9f
Revises: 
Create Date: 2025-07-18 13:55:31.305495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebbdcf51b9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the temporary table if it exists
    try:
        op.drop_table('_alembic_tmp_assignment_submission')
    except:
        pass
    
    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # Skip the foreign key constraint operations that are causing issues
    # with op.batch_alter_table('chat_message', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('chat_settings', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_file_sharing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_emoji', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('max_message_length', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.drop_column('max_message_length')
        batch_op.drop_column('allow_emoji')
        batch_op.drop_column('allow_file_sharing')
        batch_op.drop_column('chat_enabled')

    # Skip the foreign key constraint operations that are causing issues
    # with op.batch_alter_table('chat_settings', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'])

    # with op.batch_alter_table('chat_message', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'])

    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # Skip creating the temporary table
    # op.create_table('_alembic_tmp_assignment_submission', ...)
    # ### end Alembic commands ###
