"""add details

Revision ID: 32c61b62e62d
Revises: 052efd1db35d
Create Date: 2025-05-10 01:15:46.045667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c61b62e62d'
down_revision = '052efd1db35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('attachment_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'attachment_url')
    # ### end Alembic commands ###
