"""add 123 

Revision ID: 8d3ad43a342b
Revises: 1ebbdcf51b9f
Create Date: 2025-07-26 03:17:31.134696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3ad43a342b'
down_revision = '1ebbdcf51b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chat_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'])

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'])

    # ### end Alembic commands ###
