"""add phone field to contact model

Revision ID: c7b3e0a6a99c
Revises: 32c61b62e62d
Create Date: 2025-05-16 17:05:23.522424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b3e0a6a99c'
down_revision = '32c61b62e62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'phone')
    # ### end Alembic commands ###
