"""first migrate

Revision ID: c8e502883dca
Revises: 
Create Date: 2025-05-03 18:19:19.821703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8e502883dca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_allowed_user')
    op.add_column('chat_settings', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('chat_settings', sa.Column('is_enabled', sa.Boolean(), nullable=True))
    op.drop_column('chat_settings', 'chat_enabled')
    op.drop_column('chat_settings', 'allow_file_sharing')
    op.drop_column('chat_settings', 'chat_image')
    op.drop_column('chat_settings', 'allow_student_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_settings', sa.Column('allow_student_images', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('chat_settings', sa.Column('chat_image', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('chat_settings', sa.Column('allow_file_sharing', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('chat_settings', sa.Column('chat_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('chat_settings', 'is_enabled')
    op.drop_column('chat_settings', 'image_url')
    op.create_table('chat_allowed_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('chat_settings_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('added_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('added_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['user.id'], name='chat_allowed_user_ibfk_3'),
    sa.ForeignKeyConstraint(['chat_settings_id'], ['chat_settings.id'], name='chat_allowed_user_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='chat_allowed_user_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
