"""Add is_verified field to User model

Revision ID: f8b0eb7037a8
Revises: livestream_001
Create Date: 2025-07-15 09:27:19.759236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b0eb7037a8'
down_revision = 'livestream_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_assignment_submission')
    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chat_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('chat_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'])

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'])

    with op.batch_alter_table('assignment_submission', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_assignment_submission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('enrollment_id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('submission_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('submission_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('grade', sa.INTEGER(), nullable=True),
    sa.Column('feedback', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['classroom_enrollment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
